Repository a-little-org-called-mario/a-little-game-called-mario, pull requests merged in 2022-04, with the labels that each got.

#83 Adding internationalization; moving credits to txt, adding credits input
  .github/workflows/build-and-publish.yml
  .github/workflows/build-pull-request.yml
  Achievements/Level0/Level0_Coins.tres
  Achievements/Level1/Level1_Coins.tres
  Achievements/Level2/Level2_Coins.tres
  credits.csv.import
  credits.en.translation
  credits.txt
  export_presets.cfg
  localization/loca.csv
  localization/loca.csv.import
  localization/loca.de.translation
  localization/loca.en.translation
  project.godot
  scenes/Credits.gd
  scenes/Credits.tscn
  scenes/title/TitleScreen.tscn
  ui/AchievementGet.gd
  ui/CoinCount.gd
  ui/LevelCount.gd
  ui/UI.tscn
  ui/scripts/TranslatedRichTextLabel.gd
Labels: merge conflicts

#139 Added Mario Health! And Bub bullets now tilt with the screen like the coin projectiles
  autoload/EventBus.gd
  scenes/enemies/Bullet.tscn
  scenes/levels/Default2/Level04.tscn
  scenes/levels/Default3/Level05.tscn
  scripts/Bub.gd
  scripts/Bullet.gd
  scripts/Player.gd
  scripts/boxes/DisappearingPlatform.gd
  scripts/levels/Hub.gd
  ui/HeartCount.gd
  ui/UI.tscn
Labels: merge conflicts

#170 Generate credits.txt using the Github API
  .github/workflows/build-and-publish.yml
  .github/workflows/build-pull-request.yml
  autoload/GitHubAPI.gd
  project.godot
  scenes/title/Contributors.gd
  scenes/title/SmolCreditsLabel.gd
  scenes/title/TitleScreen.tscn
Labels: merge conflicts

#46 Give Mario a little jerk.
  project.godot
  scripts/AxisMotion.gd
  scripts/Player.gd
Labels: merge conflicts

#209 Improve Dance Mode
  gamemodes/DDR/Controls.gd
  gamemodes/DDR/Level.gd
  gamemodes/DDR/TrackParser.gd
  gamemodes/DDR/dance_actor/DanceActor.gd
  gamemodes/DDR/dance_actor/DanceActor.tscn
  gamemodes/DDR/track/Track.gd
  gamemodes/DDR/track/Track.tscn
  gamemodes/DDR/track/ddr.png
  gamemodes/DDR/track/ddr.png.import
  gamemodes/DDR/track/note/Down.tscn
  gamemodes/DDR/track/note/Left.tscn
  gamemodes/DDR/track/note/Note.gd
  gamemodes/DDR/track/note/Right.tscn
  gamemodes/DDR/track/note/Up.tscn
  music/dramaticgamemusic_no_loop.mp3
  music/dramaticgamemusic_no_loop.mp3.import
  project.godot
  scenes/levels/DDR_01/EnemyTrackData.txt
  scenes/levels/DDR_01/Level.gd
  scenes/levels/DDR_01/Level.tscn
  scenes/levels/DDR_01/PlayerTrackData.txt
  scenes/levels/DDR_01/track/note/Down.tscn
  scenes/levels/DDR_01/track/note/Left.tscn
  scenes/levels/DDR_01/track/note/Note.gd
  scenes/levels/DDR_01/track/note/Right.tscn
  scenes/levels/DDR_01/track/note/Up.tscn
Labels: merge conflicts

#269 fix for missing credits.txt error
  scenes/title/Contributors.gd
  scripts/Credits.gd
Labels: skip release

#283 remove requirement for levels to be tilemap-based
  scripts/Main.gd
Labels: skip release

#287 add marwing
  models/marwing/10_WATER.mtl
  models/marwing/10_WATER.obj
  models/marwing/10_WATER.obj.import
  models/marwing/10_WATER.tres
  models/marwing/MARWING.mtl
  models/marwing/MARWING.obj
  models/marwing/MARWING.obj.import
  models/marwing/MARWING_hurtmat.tres
  models/marwing/MARWING_mat.tres
  project.godot
  scenes/marwing/Marwing.tscn
  scenes/marwing/levels/1-0.tscn
  scenes/title/MarwingButton.gd
  scenes/title/TitleScreen.tscn
  scripts/marwing/Marwing.gd
  scripts/marwing/MarwingLevel.gd
  scripts/marwing/levels/1-0.gd
  sprites/marwing/EXPLODE1.png
  sprites/marwing/EXPLODE1.png.import
  textures/marwing/10_WATER.png
  textures/marwing/10_WATER.png.import
  textures/marwing/MARWING.png
  textures/marwing/MARWING.png.import
  textures/marwing/SKY.png
  textures/marwing/SKY.png.import
  textures/marwing/WORLD1.tres
Labels: bug

#296 Disable CRT filter and Camera lean by default
  scenes/ui/PauseMenu.tscn
  scripts/autoload/Settings.gd
Labels: invalid

#301 Move all audio files under an audio/ folder
  audio/music/dramaticgamemusic.mp3
  audio/music/dramaticgamemusic.mp3.import
  audio/music/dramaticgamemusic_no_loop.mp3
  audio/music/dramaticgamemusic_no_loop.mp3.import
  audio/music/givehimagun.mp3
  audio/music/givehimagun.mp3.import
  audio/music/platformer.mp3
  audio/music/platformer.mp3.import
  audio/sfx/buh.wav
  audio/sfx/buh.wav.import
  audio/sfx/coin.wav
  audio/sfx/coin.wav.import
  audio/sfx/coinflip.wav
  audio/sfx/coinflip.wav.import
  audio/sfx/fire_whoosh.wav
  audio/sfx/fire_whoosh.wav.import
  audio/sfx/hit.wav
  audio/sfx/hit.wav.import
  audio/sfx/jump.wav
  audio/sfx/jump.wav.import
  audio/sfx/meow.wav
  audio/sfx/meow.wav.import
  audio/sfx/player-hurt.wav
  audio/sfx/player-hurt.wav.import
  audio/sfx/pop-gun.wav
  audio/sfx/pop-gun.wav.import
  audio/sfx/portal.wav
  audio/sfx/portal.wav.import
  music/dramaticgamemusic.mp3.import
  music/dramaticgamemusic_no_loop.mp3.import
  music/givehimagun.mp3.import
  music/platformer.mp3.import
  scenes/Coin/Coin.tscn
  scenes/CoinProjectile.tscn
  scenes/EndPortal.tscn
  scenes/IntralevelPortal.tscn
  scenes/Main.tscn
  scenes/Player.tscn
  scenes/Star/Star.tscn
  scenes/boxes/BaseBox.tscn
  scenes/boxes/CoinBox.tscn
  scenes/enemies/Bub.tscn
  scenes/levels/DDR_01/Level.tscn
  scenes/powerups/Fireball.tscn
  scenes/title/TitleScreen.tscn
  scripts/Main.gd
Labels: skip release

#346 music donations
  .asset_donations/dullen.mp3
  .asset_donations/oh goodness (polite).mp3
  .asset_donations/oh goodness.mp3
  .asset_donations/rok.mp3
Labels: skip release

#347 Grapeburst Pie
  .asset_donations/Boom pie-Sheet.png
  .asset_donations/Grapeburst  Pie-Sheet.png
Labels: skip release

#348 Trying to resolve eol issues
  .editorconfig
  .gitattributes
  scripts/autoload/Settings.gd
  scripts/resources/Gravity.gd
Labels: skip release

#368 marwing: add missing .imports
  audio/voice/marwing/en/MW1-0_LR1.wav.import
  audio/voice/marwing/en/MW1-0_LR2.wav.import
  audio/voice/marwing/en/MW1-0_LR3.wav.import
  audio/voice/marwing/en/MW1-0_LR4.wav.import
  audio/voice/marwing/en/MW1-0_LR5.wav.import
  audio/voice/marwing/en/MW1-0_LR6.wav.import
  audio/voice/marwing/en/MW1-0_LR7.wav.import
  sprites/marwing/DIALOGUE_FRAME.png.import
  sprites/marwing/DIALOGUE_ICON--FRAME.png.import
  sprites/marwing/DIALOGUE_ICON--LRANDALL.png.import
  sprites/marwing/DIALOGUE_ICON--TICK.png.import
Labels: skip release

#251 New & improved flappy mario
  localization/loca.csv
  project.godot
  scenes/SceneTransition/SceneTransition.gd
  scenes/levels/Flappy/Characters/Obstacles/Pipes.tscn
  scenes/levels/Flappy/Characters/Player/PlayerFlying.tscn
  scenes/levels/Flappy/Characters/Player/PlayerFlyingControls.gd
  scenes/levels/Flappy/Flappy01.tscn
  scenes/levels/Flappy/UI_flappy.tscn
  scenes/levels/Flappy/UI_flappy_gameover.gd
  scenes/levels/Flappy/UI_flappy_gameover.tscn
  scenes/levels/Flappy/env/cloud.gd
  scenes/levels/Flappy/env/cloud.tscn
  scenes/levels/Flappy/env/env_spawner.gd
  sprites/mario_tiles.png
  sprites/mario_tiles.png.import
Labels: merge conflicts

#385 CameraFollow now works when solo-playing scene 🎥
  scenes/levels/CameraFollow.gd
Labels: skip release

#411 Gave the basic star tile an actual slope
  .asset_donations/star half tile.png
Labels: question

#390 The actual "mario not in bus" sprite
  .asset_donations/just Bus-export.png
Labels: skip release

#412 Fetch paginated credits from GitHub API.
  .github/workflows/build-and-publish.yml
  .github/workflows/build-pull-request.yml
  .github/workflows/update-credits.js
Labels: skip release

#441 Sokoban Volcano sprites v1
  .asset_donations/Volcano tiles background.png
  .asset_donations/Volcano tiles-export.gif
  .asset_donations/Volcano.png
Labels: skip release

#352 Started Making Some Kind of RPG Battle System
  project.godot
  scenes/battle/Member.tscn
  scenes/battle/TestBattle.tscn
  scenes/title/TitleScreen.tscn
  scenes/ui/battle/MoveButton.tscn
  scenes/ui/battle/Moves.tscn
  scripts/battle/Member.gd
  scripts/battle/MoveButton.gd
  scripts/battle/Moves.gd
  scripts/resources/Gravity.gd
  sprites/battle/attackIcons.png
  sprites/battle/attackIcons.png.import
  sprites/battle/plumber_battle.png
  sprites/battle/plumber_battle.png.import
Labels: merge conflicts

#449 Add Github Action that verifies dialogs follow correct schema
  .github/workflows/check-dialogs.yml
Labels: skip release, skip preview

#461 Disable some warnings and resolve a bunch
  project.godot
  scenes/DDR/Controls.gd
  scenes/DDR/Level.gd
  scenes/DDR/TrackParser.gd
  scenes/DDR/track/note/Note.gd
  scenes/EndPortal.gd
  scenes/levels/CharsLevels/LevelChar00.gd
  scenes/levels/Flappy/UI_flappy_gameover.gd
  scenes/levels/FollowTrigger.gd
  scenes/platformer/BigButton.gd
  scenes/platformer/characters/Trail.gd
  scenes/ui/AchievementGet.gd
  scenes/ui/Toasty.gd
  scripts/Achievement.gd
  scripts/BallPlayer.gd
  scripts/CoinsAchievement.gd
  scripts/Enemy.gd
  scripts/Main.gd
  scripts/ShootAchievement.gd
  scripts/WallMech.gd
  scripts/levels/CarMarioLevel.gd
  scripts/resources/Gravity.gd
  scripts/typeshoot/TypeShootLevel.gd
Labels: skip release

#463 Add FireMech enemy
  scenes/enemies/FireMech.gd
  scenes/enemies/FireMech.tscn
  scenes/enemies/WallMech.tscn
  scenes/levels/CharsLevels/LevelChar00.gd
  scenes/levels/CharsLevels/LevelChar00.tscn
  scripts/WallMech.gd
  sprites/Fire Mech.png
  sprites/Fire Mech.png.import
Labels: merge conflicts

#471 Fix dialog JSON looking using wrong schema path
  .github/workflows/check-dialogs.yml
Labels: skip release, skip preview
